# Generated by Django 6.1 on 2026-08-19 14:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='Variety, harvest date, storage notes -- anything a buyer would ask.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit, in Naira.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('bag', 'Bag'), ('basket', 'Basket'), ('crate', 'Crate'), ('bunch', 'Bunch'), ('piece', 'Piece'), ('litre', 'Litre')], default='kg', max_length=10)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='listings/%Y/%m/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this listing without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='listings_li_is_acti_6faa8a_idx')],
            },
        ),
    ]
