# Generated by Django 6.1 on 2026-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_credit',
            field=models.CharField(blank=True, help_text='Photographer and licence, shown under the picture. Required for Creative Commons images; leave blank for a photo the farmer took.', max_length=255),
        ),
    ]
