# Generated by Django 6.1 on 2026-08-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_image_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_alt',
            field=models.CharField(blank=True, help_text='What the photo shows, for people using a screen reader. Describe the picture, not the produce -- "a full basket of red tomatoes on a wooden table", not just the title.', max_length=180, verbose_name='Photo description'),
        ),
    ]
